# Generated by Django 3.1.3 on 2020-12-30 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201229_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='userimage',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
