# Generated by Django 3.1.3 on 2020-12-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
